spring.application.name=demo
nvd.api.key=${NVD_API_KEY}
openai.api.key=${OPENAI_API_KEY}
openai.model=gpt-4.1-mini
# openai.api.url=http://localhost:8080/test429

#spring.profiles.active=dev
#Avkommentera raden ovan för att aktivera test-endpoints och utvecklingskomponenter.